---

- name: install pkgs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - gnupg

- name: Write apt_auth for repo
  ansible.builtin.template:
    dest: "/etc/apt/auth.conf.d/nexus.conf"
    src: "apt_auth.conf.j2"
    mode: 0600

- name: Install apt repo signing key
  ansible.builtin.apt_key:
    data: "{{ lookup('ansible.builtin.file', 'production.asc') }}"
    state: present

- name: Install apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=all,amd64] https://nexus.thesrv.de/repository/production {{ ansible_distribution_release }} main"
    filename: "production"








